### ISSUE TITLE
Incorrect when used as global (ambient)

### ISSUE THREAD

**Issue by unional** [andrew-w-ross/typings-expect#1]
When I install this as a global (ambient) package (`typings install --ambient global!expect`), the global `expect` is not a function.

cc @blakeembrey for ideas

**Comment by blakeembrey** [comment]
Yeah, it has no global function defined. IIRC, it's in the `global` folder as a hack for augmentation. Can this work with 1.8 augmentation now?

**Comment by andrew-w-ross** [comment]
Ah I didn't see this, ok let me attempt to change it.
